site_name: HackTester

docs_dir: 'mkdocs'
site_dir: 'docs/static/mkdocs_build'

pages:
  - Home: index.md
  - Management commands: management_commands.md
  - API: api.md
  - Test Client : test_client.md

theme: readthedocs
